language: node_js
node_js: "14.4.0"

install:
  - npm install

script:
  - npm run build

cache:
  directories:
    - node_modules

deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: wawrzyniak.dev
  on:
    branch: master
